/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    fontFamily: {
      siteFont: ["'Poppins'", "'Arial'", "sans-serif"],
    },
    colors: {
      transparent: "transparent",
      white: "#fff",
      black: "#192A3E",
      darkText: "#334D6E",
      accentBlue: "#109CF1",
      lightGray: "#EEEEEE",
      red: "#F7685B",
      green: "#2ED47A",
      gray: "#90A0B7",
      iconGray: "#C2CFE0",
    },
    screens: {
      desctopMax: { max: "1550px" },
      desktopLg: { max: "1240px" },
      desktopMid: { max: "1161px" },
      desktopMd: { max: "1025px" },
      tabletLgMax: { max: "987px" },
      tabletLgMd: { max: "950px" },
      tabletLg: { max: "940px" },
      desktopSm: { max: "910px" },
      desktopMin: { max: "865px" },
      tabletMax: { max: "794px" },
      maxSm: { max: "768px" },
      mobileMax: { max: "675px" },
      mobileLg: { max: "545px" },
      mobileMd: { max: "400px" },
      mobileSm: { max: "365px" },
      xs: "480px",
      ss: "620px",
      sm: "769px",
      md: "1060px",
      lg: "1200px",
      xl: "1700px",
    },
    extend: {},
  },
  plugins: [],
};
